### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by samlinux** [Code-and-State/motoko-bootcamp-workspace#1]
Hi Seb,
I‘m not sure what to review for now. I would suggest, if you have finished something and want a review to a certain point, then you could open an issue and assign this issue to me and will do the review.

**Comment by seb-icp** [comment]
Hey @samlinux 
Yes, I'm working on several things at the same time, so the repository is a bit confusing for the time being. I'll ping you back once it's more advanced. 

Thanks for the support!
